version: 2
jobs:
  build:
    parallelism: 4
    docker:
      - image: circleci/ruby:2.2.10-node-browsers
        environment:
          NODE_VERSION: 5.12.0
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: ofn
          RAILS_ENV: test
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_DB: open_food_network_test
          POSTGRES_USER: ofn
          POSTGRES_PASSWORD: 'f00d'

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install latest Chromedriver
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update || true
            sudo apt-get install google-chrome-stable

      - run:
          name: Install bundler
          command: gem install bundler -v 1.17.2

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - bundler-cache-{{ checksum "Gemfile.lock" }}
            - bundler-cache-

      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: bundler-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Copy application.yml
          command: cp config/application.yml.example config/application.yml

      - run:
          name: Setup npm
          command: if [[ "$CIRCLE_NODE_INDEX" == "0" ]] ; then sudo npm install -g npm@'3.8.8' ; fi

      - run:
          name: Install npm packages
          command: if [[ "$CIRCLE_NODE_INDEX" == "0" ]] ; then npm install ; fi

      - run:
          name: Install karma
          command: if [[ "$CIRCLE_NODE_INDEX" == "0" ]] ; then sudo npm install -g karma-cli@0.1.2 ; fi

      - run:
          name: Run karma
          command: if [[ "$CIRCLE_NODE_INDEX" == "0" ]] ; then bundle exec rake karma:run ; fi

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bundle exec rake db:create db:schema:load

      - run:
          name: Run rspec in parallel
          command: bundle exec rake 'knapsack:rspec[--tag ~performance --format progress -p]'
